version: "3.6"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
      VERSION: docker
    network_mode: host
    # devices:
    #   - /dev/dri:/dev/dri
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/plex/config:/config
      - ${PATH_TO_MOVIES}:/movies
      - ${PATH_TO_TV_SHOWS}:/tv
  requestrr:
    image: darkalfx/requestrr:latest
    container_name: requestrr
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/requestrr:/root/config
    ports:
      - 4545:4545
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/bazarr/config:/config
      - ${PATH_TO_MOVIES}:/movies
      - ${PATH_TO_TV_SHOWS}:/tv
    ports:
      - 6767:6767
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn # or wireguard
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_REGIONS}
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/prowlarr/config:/config
    ports:
      - 9696:9696
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: always
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
      WEBUI_PORT: 8080
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/qbittorrent/config:/config
      - ${PATH_TO_DOCKER_DIRECTORY}/qbittorrent/downloads:/downloads
      - ${PATH_TO_MOVIES}:/movies
      - ${PATH_TO_TV_SHOWS}:/tv
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/sonarr/config:/config
      - ${PATH_TO_DOCKER_DIRECTORY}/qbittorrent/downloads:/downloads
      - ${PATH_TO_TV_SHOWS}:/tv
    ports:
      - 8989:8989
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/qbittorrent/downloads:/downloads
      - ${PATH_TO_MOVIES}:/movies
      - ${PATH_TO_DOCKER_DIRECTORY}/radarr/config:/config
    ports:
      - 7878:7878
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/tautulli/config:/config
    ports:
      - 8181:8181
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    restart: always
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/overseerr/config:/config
    ports:
      - 5055:5055
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/data:/data
      - ${PATH_TO_DOCKER_DIRECTORY}/letsencrypt:/etc/letsencrypt
  rtmp:
    image: tiangolo/nginx-rtmp
    container_name: rtmp
    restart: always
    ports:
      - 1935:1935
