version: "3.6"

services:
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
      VERSION: docker
    network_mode: host
    # devices:
    #   - /dev/dri:/dev/dri
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/plex/config:/config
      - ${PATH_TO_MOVIES}:/movies
      - ${PATH_TO_TV_SHOWS}:/tv
    restart: unless-stopped
  requestrr:
    container_name: requestrr
    image: darkalfx/requestrr:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/requestrr:/root/config
    ports:
      - 4545:4545
    restart: unless-stopped
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/bazarr/config:/config
      - ${PATH_TO_MOVIES}:/movies
      - ${PATH_TO_TV_SHOWS}:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    container_name: vpn
    cap_add:
      - NET_ADMIN # Required
      - NET_RAW # Required
    environment: # Review https://github.com/bubuntux/nordvpn#environment-variables
      TOKEN: ${NORDVPN_TOKEN} # Required
      CONNECT: United_States
      TECHNOLOGY: NordLynx
      NETWORK: 192.168.1.65 # So it can be accessed within the local network
    ports:
      - 8080:8080
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # Recomended if using ipv4 only
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    depends_on:
      - vpn
    network_mode: service:vpn
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
      WEBUI_PORT: 8080
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/qbittorrent/config:/config
      - ${PATH_TO_DOCKER_DIRECTORY}/qbittorrent/downloads:/downloads
      - ${PATH_TO_MOVIES}:/movies
      - ${PATH_TO_TV_SHOWS}:/tv
    restart: unless-stopped
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/sonarr/config:/config
      - ${PATH_TO_DOCKER_DIRECTORY}/qbittorrent/downloads:/downloads
      - ${PATH_TO_TV_SHOWS}:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/qbittorrent/downloads:/downloads
      - ${PATH_TO_MOVIES}:/movies
      - ${PATH_TO_DOCKER_DIRECTORY}/radarr/config:/config
    ports:
      - 7878:7878
    restart: unless-stopped
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ_IDENTIFIER}
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ${PATH_TO_DOCKER_DIRECTORY}/data:/data
      - ${PATH_TO_DOCKER_DIRECTORY}/letsencrypt:/etc/letsencrypt
  rtmp:
    image: tiangolo/nginx-rtmp
    container_name: rtmp
    ports:
      - 1935:1935
